{
    'name': 'Bloopark Theme',
    'summary': 'Designed By Adiclas',
    'description': 'Theme developed and designed for demo site',
    'category': 'Hidden',
    'version': '1.0',
    'author': 'ADICLAS',
    'depends': ['website'],
    'data': [ 
        'views/layout.xml',
        'views/pages.xml',
        # Assets
        'views/assets.xml',
        'views/s_address_topnav.xml',
        'views/s_services_hero.xml',
        'views/s_inner_hero.xml',
        'views/s_hero_about.xml',
        'views/s_hero_about_2.xml',
        'views/s_bgi_cover_fixed.xml',
        'views/s_our_clients.xml',
        'views/s_references.xml',
        'views/s_portfolio.xml',
        'views/s_click_to_call.xml',
        'views/s_home_video.xml',
     ],
    "icon": 'theme_bloopark/static/src/img/icon.png',
    "icon_image": 'theme_bloopark/static/src/img/icon.png',
    'application': False,
}
